<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\PeakService.Application\PeakService.Application.csproj" />
        <ProjectReference Include="..\..\..\common-library\Common\Common.Infrastructure\Common.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Http.Resilience" />
        <PackageReference Include="NetTopologySuite" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL.NetTopologySuite" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="PeakService.IntegrationTests" />
    </ItemGroup>

</Project>
