// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using PeakService.Infrastructure.Persistence;

#nullable disable

namespace PeakService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PeakDbContext))]
    [Migration("20260724204358_AddPeakIngestion")]
    partial class AddPeakIngestion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Common.Infrastructure.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAtUtc")
                        .HasDatabaseName("ix_outbox_messages_processed_at_utc");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("PeakService.Domain.MountainRanges.MountainRange", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentRangeId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_range_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("ParentRangeId");

                    b.ToTable("mountain_ranges", (string)null);
                });

            modelBuilder.Entity("PeakService.Domain.PeakIngestionRuns.PeakIngestionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at_utc");

                    b.Property<int>("PeaksCreated")
                        .HasColumnType("integer")
                        .HasColumnName("peaks_created");

                    b.Property<int>("PeaksFailed")
                        .HasColumnType("integer")
                        .HasColumnName("peaks_failed");

                    b.Property<int>("PeaksUpdated")
                        .HasColumnType("integer")
                        .HasColumnName("peaks_updated");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Status", "StartedAtUtc")
                        .HasDatabaseName("ix_peak_ingestion_runs_status_started");

                    b.ToTable("peak_ingestion_runs", (string)null);
                });

            modelBuilder.Entity("PeakService.Domain.Peaks.Peak", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AltitudeMeters")
                        .HasColumnType("integer")
                        .HasColumnName("altitude_m");

                    b.Property<Point>("Coordinates")
                        .IsRequired()
                        .HasColumnType("geography (Point,4326)")
                        .HasColumnName("location");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("country_code")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int?>("ProminenceMeters")
                        .HasColumnType("integer")
                        .HasColumnName("prominence_m");

                    b.Property<Guid?>("RangeId")
                        .HasColumnType("uuid")
                        .HasColumnName("range_id");

                    b.Property<string>("Region")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("region");

                    b.Property<string>("SourceRevision")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_revision");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("WikidataId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("wikidata_id");

                    b.Property<NpgsqlTsVector>("search_vector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("to_tsvector('simple', immutable_unaccent(name))", true);

                    b.HasKey("Id");

                    b.HasIndex("AltitudeMeters")
                        .IsDescending()
                        .HasDatabaseName("ix_peaks_altitude");

                    b.HasIndex("Coordinates")
                        .HasDatabaseName("ix_peaks_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Coordinates"), "gist");

                    b.HasIndex("CountryCode")
                        .HasDatabaseName("ix_peaks_country");

                    b.HasIndex("RangeId");

                    b.HasIndex("WikidataId")
                        .IsUnique()
                        .HasDatabaseName("ux_peaks_wikidata");

                    b.HasIndex("search_vector")
                        .HasDatabaseName("ix_peaks_search");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("search_vector"), "gin");

                    b.ToTable("peaks", (string)null);
                });

            modelBuilder.Entity("PeakService.Domain.MountainRanges.MountainRange", b =>
                {
                    b.HasOne("PeakService.Domain.MountainRanges.MountainRange", null)
                        .WithMany()
                        .HasForeignKey("ParentRangeId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PeakService.Domain.Peaks.Peak", b =>
                {
                    b.HasOne("PeakService.Domain.MountainRanges.MountainRange", null)
                        .WithMany()
                        .HasForeignKey("RangeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsMany("PeakService.Domain.Peaks.PeakName", "AlternativeNames", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<bool>("IsOfficial")
                                .HasColumnType("boolean")
                                .HasColumnName("is_official");

                            b1.Property<string>("LanguageCode")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("character varying(12)")
                                .HasColumnName("language_code");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("name");

                            b1.Property<Guid>("peak_id")
                                .HasColumnType("uuid")
                                .HasColumnName("peak_id");

                            b1.HasKey("Id");

                            b1.HasIndex("peak_id")
                                .HasDatabaseName("ix_peak_names_peak");

                            b1.HasIndex("peak_id", "LanguageCode", "Name")
                                .IsUnique()
                                .HasDatabaseName("ux_peak_names_unique");

                            b1.ToTable("peak_names", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("peak_id");
                        });

                    b.Navigation("AlternativeNames");
                });
#pragma warning restore 612, 618
        }
    }
}
